#!/bin/sh /etc/rc.common
# Copyright (C) 2023 Tianling Shen <cnsztl@immortalwrt.org>

USE_PROCD=1
START=99

CONF="dae"
PROG="/usr/bin/dae"
LOG="/var/log/dae.log"

EXTRA_COMMANDS="reload_config"
EXTRA_HELP="        reload_config   Reload dae configuration"

start_service() {
	config_load "$CONF"

	local enabled
	config_get_bool enabled "config" "enabled" "0"
	[ "$enabled" -eq "1" ] || return 1

	local config_file
	config_get config_file "config" "config_file" "/etc/dae/config.dae"

	"$PROG" validate -c "$config_file" || return 1

	procd_open_instance "$CONF"
	procd_set_param env QUIC_GO_ENABLE_GSO=true
	procd_set_param command "$PROG"
	procd_append_param command run --logfile "$LOG" -c "$config_file"

	local size
	config_get size config logfile_maxsize 4
	case "$size" in
		''|*[!0-9]*) size=4 ;;
	esac
	[ "$size" -gt 0 ] && procd_append_param command --logfile-maxsize "$size"

	procd_set_param limits core="unlimited"
	procd_set_param limits nofile="1000000 1000000"
	procd_set_param respawn
	# procd_set_param stdout 1
	procd_set_param stderr 1

	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "$CONF"
}

reload_service() {
	stop
	sleep 1
	start
}

reload_config() {
	"$PROG" reload
}
